---
name: Pull Requester

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled
    branches:
      - main

concurrency:
  # Ensure that only a single concurrent job is run for any Pull Requester
  # GitHub Workflow on any one pull request (or github.event.number here)
  group: pull-requester-${{ github.event.number }}

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write

jobs:
  pull-requester:
    runs-on: ubuntu-latest
    name: Check the Pull Request

    steps:
      - name: Pull Requester
        uses: n3tuk/action-pull-requester@v1
